In [33]:
# Importar pacote
import pandas as pd

In [34]:
# Extrair dados
livros_populares = pd.read_csv('Amazon_popular_books_dataset_tratado.csv')

In [35]:
# Definir uma classe
class CatalogoLivros:
    def __init__(self, dataframe):
        self.catalogo = dataframe

    def adicionar_livro(self, novo_livro):
        # Adicionar uma nova linha ao DataFrame
        self.catalogo = self.catalogo.append(novo_livro, ignore_index=True)

    def excluir_livro_por_indice(self, indice):
        # Excluir uma linha do DataFrame com base no índice
        self.catalogo = self.catalogo.drop(index=indice).reset_index(drop=True)

    def listar_livros(self):
        # Listar informações de todos os livros no catálogo
        return self.catalogo

In [36]:
# Criar catálogo de livros
catalogo = CatalogoLivros(livros_populares)

In [37]:
# Excluir um livro por índice (por exemplo, o primeiro livro)
catalogo.excluir_livro_por_indice(0)

In [38]:
# Listar todos os livros no catálogo
catalogo.listar_livros()

,ISBN10,title,brand,discount,initial_price,final_price
0,0060244887,The Chronicles of Narnia (Box Set),C. S. Lewis,66.01,120.00,53.99
1,0060254920,Where the Wild Things Are,Maurice Sendak,6.75,19.95,13.20
2,0060256656,The Giving Tree,Shel Silverstein,8.90,17.99,9.09
3,9780060555665,The Intelligent Investor Rev Ed.: The Definiti...,Benjamin GrahamJason Zweig,10.70,24.99,14.29
4,0060652888,Mere Christianity,C. S. Lewis,2.50,24.99,22.49
...,...,...,...,...,...,...
1171,9789386217967,Diagnostic and Statistical Manual of Mental Di...,by The Committee on Nomenclature and Statistic...,7.03,35.98,28.95
1172,9789387779266,My First Library : Boxset of 10 Board Books fo...,Wonder House Books,2.00,19.99,17.99
1173,NaN,200 Must Know Sight Words Activity Workbook: L...,Smart Kids Notebooks,1.00,6.99,5.99
1174,1419741853,Diary of a Wimpy Kid (Diary of a Wimpy Kid #1),Jeff Kinney,5.51,14.99,9.48
1175,1419741934,The Third Wheel (Diary of a Wimpy Kid #7),Jeff Kinney,6.00,14.99,8.99

In [39]:
# Adicionar um novo livro ao catálogo
novo_livro = {
    'ISBN10': '0007350813',
    'title': 'Wuthering Heights (Collins Classics)',
    'brand': 'Emily Brontë',
    'discount': 1.06,
    'initial_price': 7.99,
    'final_price': 6.93,
}

catalogo.adicionar_livro(novo_livro)

C:\Users\Mike\AppData\Local\Temp\ipykernel_34608\2545041444.py:8: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  self.catalogo = self.catalogo.append(novo_livro, ignore_index=True)

In [44]:
# Listar todos os livros no catálogo após a exclusão
nova_arquivo = catalogo.listar_livros()

In [45]:
# Salvar o DataFrame resultante no arquivo CSV
nova_arquivo.to_csv('Amazon_popular_books_dataset_processado.csv', index = False)